### ISSUE TITLE
怎么用usb链接呢

### ISSUE THREAD

**Issue by freebughao** [scavin/ws-scrcpy-docker#2]
如何将主机的usb 链接的安卓设备挂载到容器内呢

**Comment by scavin** [comment]
Docker 官方解答里描述应该是不支持的。

https://docs.docker.com/desktop/faqs/general/#can-i-pass-through-a-usb-device-to-a-container

**Comment by freebughao** [comment]
> Docker 官方解答里描述应该是不支持的。
> 
> https://docs.docker.com/desktop/faqs/general/#can-i-pass-through-a-usb-device-to-a-container

感谢回答，刚放弃了docker的方式，现在在主机跑了ws-scrcpy项目，之后有时间试下usbip的效率怎么样
